name: mediapipe
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - nb_conda_kernels=2.3.1
  - opencv=4.5.2
  - pip=21.1.3
  - pip:
    - mediapipe==0.8.6
    - scikit-learn 
    - tensorflow 
    - pandas 
    - numpy 
    - h5py 
    - matplotlib
